### ISSUE TITLE
파일 업로드 에러

### ISSUE THREAD

**Issue by NaweGa** [foxtrot-99/imitated-seed-v2#10]
계속 이슈를 올려드려서 죄송합니다. <del>Node.js는 못해서...</del>
파일 업로드를 하려는데 콘솔에
                        res.on('data', chunk += data);
                            ^

ReferenceError: chunk is not defined
    at ClientRequest.<anonymous> (/server.js:5973:8)

이 에러를 장렬히 내뿜으며 업로드가 안됩니다

**Comment by foxtrot-99** [comment]
화일 올리는 기능은 아직 미구현입니다만 저게 버그는 맞으므로 고치긴 하겠습니다.

**Comment by NaweGa** [comment]
감사드립니다
