### ISSUE TITLE
include 문법

### ISSUE THREAD

**Issue by NaweGa** [foxtrot-99/imitated-seed-v2#9]
[include(문서명)]이 작동하지 않습니다.
소스를 분석해 봐야 할 것 같은데 동작 안하는 것이 맞나요?

**Comment by NaweGa** [comment]
<del>이거 라벨은 어떻게 설정하지</del>

**Comment by foxtrot-99** [comment]
아직 구현이 안 됐는데, 아직 더시드엔진이랑 다르게 작동하는 부분이랑 삼중중괄호 문법 오류 등 고쳐할 부분이 좀 많긴 합니다.

**Comment by NaweGa** [comment]
그렇군요.
<del>노가다의 시작</del>
